### ISSUE TITLE
 Saved data of the focused files/folders are outside of the project files structure 

### ISSUE THREAD

**Issue by nicolasmol** [quicken/filefocus#1]
Hi

It's shame than you save the data in using local storage service rather than in the .vscode/settings.json of the current folder. Because of this you cannot use FileFocus in conjunction with a "project templates" extension...We have to re-create new focuses each brand new project. 

Some focuses can be fixed for each project (e.g. main.dart)

Please improve this

**Comment by quicken** [comment]
Can you please elaborate on your use case? What exactly is on your wish list?

Happy to see if I can provide a setting to tweak storage options if you can give some context.

**Comment by nicolasmol** [comment]
As I tried to explain, suppose you want to create a project skeleton than you will save as a "template" for starting any new project and you also want to save the common focuses in this template (in may case for example : /lib/main.dart or android/build.gradle, and others that are common to any projects)...you can't because you save the date outside of the project structure...you save them in using vscode Storage service.

In the same manner I suppose that moving only the project's file  from a pc to another one won't keep the focuses because of this. Am i right ?

**Comment by quicken** [comment]
Interesting, I have not considered your use case. Sounds like it may be a nice addition.

**Comment by nicolasmol** [comment]
In fact, it can be considered as a bug...since as a matter of fact try this: 
- quit vscode, 
- rename a project folder
-  come back

Result: your lost your focuses

**Comment by quicken** [comment]
It is now possible to define a filefocus.json file that can be stored in the root of a workspace folder. 

This file is project specific and can be stored alongside source code in .git. The groups defined in this file are merged with focus groups stored inside the workspace state. 

Also, a new setting affords the ability to use the global state instead of the workbench state for storing focus groups.

A known issue brought about by multiple workspace folder support is that focus group resources require the workspace folder name to be the same on all devices that share the global workspace. The full file path is not relevant.
