### ISSUE TITLE
Feature suggestion: order of files

### ISSUE THREAD

**Issue by miguel-de-aXman** [quicken/filefocus#3]
File ordering in the File Focus panel is able to be re-ordered
OR 
Default order is by full path name rather than file name.

**Comment by quicken** [comment]
Fixed in 1.4.1 Beta 3 - Release to the marketplace should be within the next couple of days.

Within settings, there now exists an option to sort resources based on the basename (file name only) or by the full path of a resource.

Currently, this setting requires a restart for vscode to pick up the changes.
